### DEFAULT ###
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health
  prometheus:
    metrics:
      export:
        enabled: true

wsl:
  docker:
    filePath: /opt/hello-wsl
    fileName: Custom_Logs.log
---
### LOCAL ###
spring.config.activate.on-profile: LOCAL
server:
  port: 49999

wsl:
  docker:
    filePath: C:/Temp/Logs
    fileName: Custom_Logs.log