server:
  port: 49999

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health
  prometheus:
    metrics:
      export:
        enabled: true

wsl:
  docker:
    filePath: C:/Temp/Logs
    fileName: Custom_Logs.log