version: '3.8'

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    volumes:
      - type: volume
        source: grafana_data
        target: /var/lib/grafana
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - type: bind #- /proc:/host/proc:ro
        read_only: true
        source: /proc
        target: /host/proc
      - type: bind #- /sys:/host/sys:ro
        read_only: true
        source: /sys
        target: /host/sys
      - type: bind #- /:/rootfs:ro
        read_only: true
        source: /
        target: /rootfs
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    ports:
      - "9100:9100"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - type: bind
        source: "/mnt/c/Development/Workspace/IntelliJ/java-wsl2-sample-app/monitoring/prometheus.yml"
        target: "/etc/prometheus/prometheus.yml"
        read_only: true
      - type: volume #- prometheus_data:/prometheus
        source: prometheus_data
        target: /prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    ports:
      - "9090:9090"
    networks:
      - monitoring
