apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-wsl-app
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-wsl-app
  template:
    metadata:
      labels:
        app: hello-wsl-app
    spec:
      containers:
        - name: hello-wsl
          image: localhost:5000/hello-wsl:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 49999
---
apiVersion: v1
kind: Service
metadata:
  name: hello-wsl-internal-service
  namespace: app
spec:
  selector:
    app: hello-wsl-app
  ports:
    - protocol: TCP
      port: 49999
      targetPort: 49999
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-wsl-ingress
  namespace: app
spec:
  ingressClassName: nginx
  rules:
    - host: app.k8s.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-wsl-internal-service
                port:
                  number: 49999
