apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-wsl-app
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-wsl-app
  template:
    metadata:
      labels:
        app: hello-wsl-app
    spec:
      containers:
        - name: hello-wsl
          image: localhost:5000/hello-wsl:1.0
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /opt/hello-wsl
              name: hello-wsl-pv-storage
      volumes:
        - name: hello-wsl-pv-storage
          persistentVolumeClaim:
            claimName: hello-wsl-pv-claim
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hello-wsl-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/c/temp/k8s/hello-wsl"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-wsl-pv-claim
  namespace: app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: hello-wsl-internal-service
  namespace: app
spec:
  selector:
    app: hello-wsl-app
  ports:
    - protocol: TCP
      port: 49999
      targetPort: 8080